version: "3.9"

services:
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v22.3.11
    hostname: redpanda
    command:
      - redpanda start
      - --smp 1
      - --reserve-memory 0M
      - --overprovisioned
      - --node-id 1
      - --kafka-addr PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092
      - --pandaproxy-addr PLAINTEXT://0.0.0.0:28082,OUTSIDE://0.0.0.0:8082
      - --advertise-pandaproxy-addr PLAINTEXT://redpanda:28082,OUTSIDE://localhost:8082
      - --rpc-addr 0.0.0.0:33145
      - --advertise-rpc-addr redpanda:33145
    ports:
      - 8082:8082
      - 9092:9092
      - 28082:28082
      - 29092:29092
    healthcheck:
      test: ["CMD", "redpanda", "admin", "check"]
      interval: 5s
      timeout: 1s
      retries: 30

  
  console:
    image: docker.redpanda.com/redpandadata/console:v2.2.2
    ports:
      - 9000:8080
    environment:
      - KAFKA_BROKERS=redpanda:29092
    depends_on:
      - redpanda


  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    # volumes:
    #   - rabbitmq:/var/lib/rabbitmq/mnesia
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 1s
      retries: 30

volumes:
  redpanda:
  rabbitmq: